export interface Review {
  id: string;
  stars: number;
  title: string;
  text: string;
  author: string;
  size: string;
  verified: boolean;
  date: string;
  helpful: number;
  productSlug?: string;
}

export const reviews: Review[] = [
  {
    id: "r1",
    stars: 5,
    title: "Finally, a perfect fit",
    text: "I've been searching for a bra that truly fits for years. The Provence wired bra is perfection — the embroidery is gorgeous and the support is incredible. Worth every penny.",
    author: "Sophie M.",
    size: "80D",
    verified: true,
    date: "2026-02-14",
    helpful: 24,
    productSlug: "provence-wired-bra",
  },
  {
    id: "r2",
    stars: 5,
    title: "European quality you can feel",
    text: "The craftsmanship is on another level. You can tell each piece is made with care. The spacer bra is so comfortable I forget I'm wearing it. My new everyday bra.",
    author: "Charlotte W.",
    size: "75C",
    verified: true,
    date: "2026-01-28",
    helpful: 18,
    productSlug: "pure-feeling-spacer-bra",
  },
  {
    id: "r3",
    stars: 5,
    title: "Invisible under everything",
    text: "The Rhapsody spacer bra truly disappears under T-shirts. I ordered in Light Taupe and it's the perfect nude shade. The embroidery on the straps is a beautiful detail.",
    author: "Emma L.",
    size: "85E",
    verified: true,
    date: "2026-03-02",
    helpful: 31,
    productSlug: "rhapsody-spacer-bra",
  },
  {
    id: "r4",
    stars: 4,
    title: "Beautiful lace, great support",
    text: "The Swing collection is stunning. The Dusty Rose color is even more beautiful in person. Only reason for 4 stars is I wish they had more color options. The fit is flawless.",
    author: "Maria K.",
    size: "90D",
    verified: true,
    date: "2026-02-20",
    helpful: 12,
    productSlug: "swing-wired-bra",
  },
  {
    id: "r5",
    stars: 5,
    title: "TENCEL™ against my skin — heaven",
    text: "The Beyond Basic bra is incredibly soft. Knowing it's made with sustainable TENCEL™ from European forests makes it even better. The front closure click system is genius.",
    author: "Anna R.",
    size: "80C",
    verified: true,
    date: "2026-03-10",
    helpful: 15,
    productSlug: "beyond-basic-molded-bra",
  },
  {
    id: "r6",
    stars: 5,
    title: "Shaping without squeezing",
    text: "The Soft Touch long panty is the first shapewear I've actually wanted to wear all day. It smooths without that uncomfortable compressed feeling. Really impressive engineering.",
    author: "Helena G.",
    size: "42",
    verified: true,
    date: "2026-01-15",
    helpful: 22,
    productSlug: "soft-touch-long-panty",
  },
  {
    id: "r7",
    stars: 5,
    title: "My 80-year-old mother loves it",
    text: "I ordered the Weftloc wireless bra for my mother and she says it's the most comfortable bra she's ever worn. The broad straps take all the weight off her shoulders. Now I've ordered one for myself!",
    author: "Isabelle P.",
    size: "95D",
    verified: true,
    date: "2026-02-05",
    helpful: 27,
    productSlug: "weftloc-wireless-bra",
  },
  {
    id: "r8",
    stars: 4,
    title: "Lovely Lotus — aptly named",
    text: "The Peach Blossom color is divine. The lace is delicate but feels durable. I went with my usual EU size and it fits perfectly. Shipping from Europe was faster than expected.",
    author: "Victoria S.",
    size: "75B",
    verified: true,
    date: "2026-03-18",
    helpful: 9,
    productSlug: "lovely-lotus-wired-bra",
  },
  {
    id: "r9",
    stars: 5,
    title: "Best molded bra on the market",
    text: "I've tried countless molded bras and the Joy is hands down the best. The smooth finish under fitted tops is unmatched. The Magic Blue color is gorgeous and unique.",
    author: "Laura D.",
    size: "80D",
    verified: true,
    date: "2026-02-28",
    helpful: 19,
    productSlug: "joy-molded-bra",
  },
  {
    id: "r10",
    stars: 5,
    title: "140 years of expertise shows",
    text: "You can feel the 140 years of craftsmanship in every detail. From the embroidery to the smooth edges — nothing scratches, nothing pokes. This is what European lingerie should be.",
    author: "Catherine B.",
    size: "85F",
    verified: true,
    date: "2026-01-22",
    helpful: 33,
    productSlug: "moments-wired-bra",
  },
  {
    id: "r11",
    stars: 4,
    title: "Flora — everyday elegance",
    text: "The floral jacquard on the Flora spacer bra is subtle but beautiful. It's become my go-to everyday bra. The Bisquit color works perfectly under white tops.",
    author: "Nina H.",
    size: "80C",
    verified: true,
    date: "2026-03-05",
    helpful: 8,
    productSlug: "flora-spacer-bra",
  },
  {
    id: "r12",
    stars: 5,
    title: "Worth the investment",
    text: "I was hesitant about the price but after wearing the Serenada bra for a month, I understand the value. The jacquard material has this beautiful shimmer and the fit is impeccable. Already ordering more.",
    author: "Alexandra T.",
    size: "80E",
    verified: true,
    date: "2026-03-22",
    helpful: 14,
    productSlug: "serenada-wired-bra",
  },
];

export const brandRating = {
  average: 4.8,
  totalReviews: 2147,
  breakdown: {
    5: 82,
    4: 13,
    3: 3,
    2: 1,
    1: 1,
  },
};
